-- 20_admin_permissions.sql
-- Granular, grantable permissions for local admins. Each row is one capability
-- slug granted to one admin. SuperAdmins hold every permission implicitly and
-- are NOT represented here. Slugs are validated in application code
-- (src/config/permissions.js) so the catalog can evolve without a migration.
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS public.admin_permissions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    bigint NOT NULL REFERENCES public.admins(id) ON DELETE CASCADE,
    permission  text   NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT admin_permissions_unique UNIQUE (admin_id, permission)
);

CREATE INDEX IF NOT EXISTS idx_admin_permissions_admin ON public.admin_permissions (admin_id);
