-- 69_access_ledger.sql
-- Provenance for every admin access change.
--
-- Today `admin_permissions` holds only the CURRENT state: it says an admin holds
-- `manage_mobility`, never who granted it, when, why, or when it stops. An access
-- review (and any auditor) needs the answer to "who gave this person this power,
-- on whose authority, and until when" — so record every access transition as an
-- append-only event next to the current-state table.
--
-- Two additions, both additive and idempotent:
--
--   1. admins.access_profile — the named access profile ("dept_lead", "site_hr",
--      "country_hrbp", "governance_read") an account was last provisioned from.
--
--      *** REPORTING / DRIFT DETECTION ONLY. ***
--      This column MUST NEVER be read by an authorization guard. Authorization is
--      decided exclusively by the rows in `admin_permissions` (expanded through
--      src/config/permissions.js) plus the scope rows in `admin_scopes`. A profile
--      is a provisioning CONVENIENCE — a named bundle of slugs applied once — and
--      the grants it produced can be edited or revoked afterwards without touching
--      this column. Treating it as authority would resurrect exactly the role-shape
--      bypass that migration-era work just closed: a text label on `admins` that
--      confers power without a corresponding grant row. Its only legitimate uses
--      are (a) showing "provisioned as: Chef de departement" in the UI and (b) the
--      drift report "this account says dept_lead but no longer holds those slugs".
--
--   2. admin_access_events — one row per access transition (grant / revoke /
--      profile applied / scope added / scope removed / expiry extended), carrying
--      the actor, the reason, and the validity window.
--
--      `actor_admin_id` deliberately carries NO foreign key: the ledger must outlive
--      the account that performed the change, so deleting an admin can never cascade
--      away the evidence of what they did. `admin_id` DOES cascade — when the subject
--      account is erased (GDPR), their access history goes with them.

ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS access_profile text;

CREATE TABLE IF NOT EXISTS public.admin_access_events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id        bigint NOT NULL REFERENCES public.admins(id) ON DELETE CASCADE,
    change_type     text   NOT NULL,
    slug            text,
    scope_type      text,
    scope_id        bigint,
    profile_key     text,
    effective_from  timestamptz NOT NULL DEFAULT now(),
    effective_to    timestamptz,
    actor_admin_id  bigint,
    reason          text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_access_events_admin
    ON public.admin_access_events (admin_id, created_at DESC);
